worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;

    # ================= DEV =================
    server {
        listen 80;
        server_name dev.local;

        location / {
            proxy_pass http://frontend_dev:5173;
        }

        location /api/ {
            proxy_pass http://backend_dev:8000/;
        }
    }

    # ================= UAT =================
    server {
        listen 80;
        server_name uat.local;

        location / {
            proxy_pass http://frontend_uat:5173;
        }

        location /api/ {
            proxy_pass http://backend_uat:8000/;
        }
    }

    # ================= PROD =================
    server {
        listen 80;
        server_name prod.local;

        location / {
            proxy_pass http://frontend_prod:5173;
        }

        location /api/ {
            proxy_pass http://backend_prod:8000/;
        }
    }

    # fallback
    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://frontend_dev:5173;
        }

        location /api/ {
            proxy_pass http://backend_dev:8000/;
        }
    }
}